//! Written content, compiled into the binary at build time.
//!
//! The arrays below are generated by [`build.rs`](../build.rs) from `content/**/*.md` and
//! pulled in by the `include!` at the bottom of this file. Nothing here parses markdown:
//! by the time this module exists, every body is already HTML and every entry already
//! carries its metadata. See `docs/log-section.md` for why the parse happens at build
//! time rather than in the browser.
//!
//! To publish, drop a `.md` file into `content/log/` and rebuild — there is no other step.
//!
//! Both types are `Copy` (every field is a `'static` reference or a number), matching
//! [`crate::data::Project`], so entries pass through reactive closures without cloning or
//! lifetime annotations.

/// One `h2`/`h3` in an entry, used to build the table of contents.
///
/// `id` matches the `id` attribute on the rendered heading, so `#id` links land on it.
#[derive(Clone, Copy, PartialEq, Eq)]
pub struct Heading {
    /// Heading depth: 2 or 3. Deeper headings are rendered but kept out of the TOC.
    pub level: u8,
    /// Slugified anchor, unique within the entry.
    pub id: &'static str,
    /// Heading text, already stripped of any inline markup.
    pub text: &'static str,
}

/// A single piece of writing.
#[derive(Clone, Copy, PartialEq, Eq)]
pub struct Entry {
    /// URL segment: the filename minus its `YYYY-MM-DD-` prefix. Re-dating an entry
    /// therefore never breaks its link.
    pub slug: &'static str,
    /// Full title, shown in the index and as the page heading.
    pub title: &'static str,
    /// ISO `YYYY-MM-DD`. Validated at build time so it sorts as text.
    pub date: &'static str,
    /// One plain-text paragraph shown in the index. No markup.
    pub summary: &'static str,
    /// Lowercase topic tags, used by the index filter.
    pub tags: &'static [&'static str],
    /// Estimated reading time in minutes, at 220 wpm, never less than 1.
    pub reading_minutes: usize,
    /// The entry's `h2`/`h3` headings, in document order.
    pub headings: &'static [Heading],
    /// The rendered body, ready for `inner_html`.
    ///
    /// Safe to inject: every byte originates in a markdown file in this repo, authored
    /// by the site's owner and reviewed in git. This assumption must be revisited the
    /// day content arrives from anywhere else.
    pub html: &'static str,
}

impl Entry {
    /// Route to this entry's page.
    pub fn href(&self) -> String {
        format!("/log/{}", self.slug)
    }
}

/// Find an entry by slug — the lookup behind `/log/:slug`.
pub fn by_slug(slug: &str) -> Option<Entry> {
    LOG.iter().find(|e| e.slug == slug).copied()
}

/// The entries either side of `slug` in the list, as `(newer, older)`.
///
/// `LOG` is newest-first, so the *previous* index is the newer entry.
pub fn neighbours(slug: &str) -> (Option<Entry>, Option<Entry>) {
    let Some(i) = LOG.iter().position(|e| e.slug == slug) else {
        return (None, None);
    };
    let newer = i.checked_sub(1).and_then(|j| LOG.get(j)).copied();
    let older = LOG.get(i + 1).copied();
    (newer, older)
}

/// Every tag used across the log, deduplicated, in first-seen order.
///
/// Built on demand rather than generated: the list is short, and the index page needs it
/// exactly once per visit.
pub fn all_tags() -> Vec<&'static str> {
    let mut tags: Vec<&'static str> = Vec::new();
    for entry in LOG {
        for tag in entry.tags {
            if !tags.contains(tag) {
                tags.push(tag);
            }
        }
    }
    tags
}

// Generated by build.rs: `pub static LOG: &[Entry]`, newest first.
include!(concat!(env!("OUT_DIR"), "/entries.rs"));
